using Test
using IntervalArithmetic

@testset "rational_power_test" begin
    @test isequal_interval(^(emptyinterval(), 1//3), emptyinterval())
    @test isequal_interval(^(interval(1, 8), 1//3), interval(1, 2))
    @test issubset_interval(interval(2^(1//3), 2), ^(interval(2, 8), 1//3))
    @test issubset_interval(interval(1, 9^(1//3)), ^(interval(1, 9), 1//3))
    @test issubset_interval(interval(2^(1//3), 9^(1//3)), ^(interval(2, 9), 1//3))
    @test isequal_interval(^(interval(-1, 8), 1//3), interval(0, 2))
    @test issubset_interval(interval(0, 2), ^(interval(-2, 8), 1//3))
    @test issubset_interval(interval(0, 9^(1//3)), ^(interval(-1, 9), 1//3))
    @test issubset_interval(interval(0, 9^(1//3)), ^(interval(-2, 9), 1//3))
    @test isequal_interval(^(interval(1, 8), -1//3), interval(0.5, 1))
    @test issubset_interval(interval(0.5, 2^(-1//3)), ^(interval(2, 8), -1//3))
    @test issubset_interval(interval(9^(-1//3), 1), ^(interval(1, 9), -1//3))
    @test issubset_interval(interval(9^(-1//3), 2^(-1//3)), ^(interval(2, 9), -1//3))
    @test isequal_interval(^(interval(-1, 8), -1//3), interval(0.5, Inf))
    @test issubset_interval(interval(0.5, Inf), ^(interval(-2, 8), -1//3))
    @test issubset_interval(interval(9^(-1//3), Inf), ^(interval(-1, 9), -1//3))
    @test issubset_interval(interval(9^(-1//3), Inf), ^(interval(-2, 9), -1//3))
    @test isequal_interval(^(interval(-2, 4), 1//2), interval(0, 2))
    @test isequal_interval(^(interval(-2, 8), 1//3), interval(0, 2))
    @test isequal_interval(^(interval(-8, -2), 1//3), emptyinterval())
    @test isequal_interval(^(interval(-8, -2), 1//2), emptyinterval())
    @test isequal_interval(^(interval(-8, -2), -1//3), emptyinterval())
    @test isequal_interval(^(interval(-8, -2), -1//2), emptyinterval())
    @test isequal_interval(^(emptyinterval(), 2//3), emptyinterval())
    @test isequal_interval(^(interval(1, 8), 2//3), interval(1, 4))
    @test issubset_interval(interval(2^(2//3), 4), ^(interval(2, 8), 2//3))
    @test issubset_interval(interval(1, 9^(2//3)), ^(interval(1, 9), 2//3))
    @test issubset_interval(interval(2^(2//3), 9^(2//3)), ^(interval(2, 9), 2//3))
    @test isequal_interval(^(interval(-1, 8), 2//3), interval(0, 4))
    @test issubset_interval(interval(0, 4), ^(interval(-2, 8), 2//3))
    @test issubset_interval(interval(0, 9^(2//3)), ^(interval(-1, 9), 2//3))
    @test issubset_interval(interval(0, 9^(2//3)), ^(interval(-2, 9), 2//3))
    @test isequal_interval(^(interval(1, 8), -2//3), interval(0.25, 1))
    @test issubset_interval(interval(0.25, 2^(-2//3)), ^(interval(2, 8), -2//3))
    @test issubset_interval(interval(9^(-2//3), 1), ^(interval(1, 9), -2//3))
    @test issubset_interval(interval(9^(-2//3), 2^(-2//3)), ^(interval(2, 9), -2//3))
    @test isequal_interval(^(interval(-1, 8), -2//3), interval(0.25, Inf))
    @test issubset_interval(interval(0.25, Inf), ^(interval(-2, 8), -2//3))
    @test issubset_interval(interval(9^(-2//3), Inf), ^(interval(-1, 9), -2//3))
    @test issubset_interval(interval(9^(-2//3), Inf), ^(interval(-2, 9), -2//3))
    @test isequal_interval(^(interval(-2, 4), 3//2), interval(0, 8))
    @test isequal_interval(^(interval(-2, 8), 2//3), interval(0, 4))
    @test isequal_interval(^(interval(-8, -2), 2//3), emptyinterval())
    @test isequal_interval(^(interval(-8, -2), 3//2), emptyinterval())
    @test isequal_interval(^(interval(-8, -2), -2//3), emptyinterval())
    @test isequal_interval(^(interval(-8, -2), -3//2), emptyinterval())
    @test isequal_interval(^(interval(-1, 1), 1000000000000000000000000000000000000000//1), interval(0, 1))
end
