include_test("construction.jl")
include_test("parsing.jl")
include_test("rounding.jl")
include_test("consistency.jl")
include_test("numeric.jl")
include_test("power.jl")
include_test("trig.jl")
include_test("hyperbolic.jl")
include_test("loops.jl")
include_test("bisect.jl")
include_test("rand.jl")
include_test("display.jl")
include_test("multidim.jl")
# include_test("complex.jl") # TODO uncomment when `Complex` support is restored
