site_name: 'IntervalArithmetic.jl'

site_description: 'IntervalArithmetic.jl: A Julia package for interval arithmetic'

repo_url: https://github.com/JuliaIntervals/IntervalArithmetic.jl

pages:
    - 'Package': 'index.md'
    - 'Basic usage': 'usage.md'
    - 'Multi-dimensional': 'multidim.md'
    - 'Rounding': 'rounding.md'
    - 'Decorations': 'decorations.md'

#theme: readthedocs

#markdown_extensions: [math]

copyright: Copyright &copy; 2014-2017, Luis Benet & David P. Sanders
